'use strict';

/** Catalogue HERBALIS (€) - côlon, cheveux, respiration. */
module.exports = [
  {
    name: 'Flora Colon', name_ar: 'فلورا كولون',
    brand: 'HERBALIS', category: 'colon', price: 29.9, old_price: 34.9, stock: 48,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Inuline, Lactobacillus, Bifidobacterium',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '1 gélule matin et soir',
    short_fr: 'Microbiote intestinal, formule concentrée.',
    short_ar: 'ميكروبيوتا الأمعاء، صيغة مركّزة.',
    desc_fr: 'Flora Colon associe fibres prébiotiques (inuline) et ferments lactiques pour soutenir l\'équilibre du microbiote. Destiné aux personnes qui cherchent un confort digestif au quotidien (ballonnements, irrégularité). Gélules végétales, fabriqué en France. Ne se substitue pas à un régime varié ni à un avis médical.',
    desc_ar: 'يجمع فلورا كولون أليافاً بريبيوتيك (إينولين) وخمائر لبنية لدعم توازن الميكروبيوتا. موجّه لمن يبحث عن راحة هضمية يومية (انتفاخ، عدم انتظام). كبسولات نباتية، مصنوع في فرنسا. لا يغني عن نظام غذائي متنوع ولا عن استشارة طبية.',
    image: 'p-colon-flora.png', featured: 1, active: 1, sort_order: 1,
  },
  {
    name: 'Transit Doux', name_ar: 'ترانزيت دو',
    brand: 'HERBALIS', category: 'colon', price: 24.9, old_price: null, stock: 36,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Psyllium, fenouil, mauve',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '2 gélules le soir avec un grand verre d\'eau',
    short_fr: 'Transit intestinal, fibres et plantes douces.',
    short_ar: 'عبور معوي، ألياف ونباتات لطيفة.',
    desc_fr: 'Transit Doux combine psyllium, fenouil et mauve pour accompagner un transit plus régulier sans sensation agressive. Utile en cas de constipation occasionnelle liée au rythme de vie. À prendre avec beaucoup d\'eau. Contre-indiqué en cas d\'occlusion. Demandez conseil si vous êtes sous traitement.',
    desc_ar: 'يجمع ترانزيت دو بين السيليوم والشمر والخبازة لمرافقة عبور معوي أكثر انتظاماً دون إحساس قاسٍ. مفيد في الإمساك العارض المرتبط بنمط الحياة. يُؤخذ مع كمية وافرة من الماء. غير مناسب في حال انسداد معوي. استشر مختصاً إذا كنت تخضع لعلاج.',
    image: 'p-colon-detox.png', featured: 0, active: 1, sort_order: 2,
  },
  {
    name: 'Detox Côlon', name_ar: 'ديتوكس القولون',
    brand: 'HERBALIS', category: 'colon', price: 32.9, old_price: 38.9, stock: 28,
    cpu: '90 gélules', ram: 'Cure 45 jours', storage: 'Charbon végétal, chlorella, citron',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '2 gélules à jeun, loin des médicaments',
    short_fr: 'Détox intestinale, charbon végétal et chlorella.',
    short_ar: 'تنقية معوية، فحم نباتي وكلوريلا.',
    desc_fr: 'Detox Côlon vise à accompagner l\'élimination et le confort du côlon grâce au charbon végétal et à la chlorella. Pensé pour une cure courte après des excès alimentaires. Le charbon peut réduire l\'absorption de médicaments : écarter les prises de 2 heures. Femmes enceintes : avis médical.',
    desc_ar: 'يهدف ديتوكس القولون إلى مرافقة الإطراح وراحة القولون بفضل الفحم النباتي والكلوريلا. مصمّم لعلاجات قصيرة بعد الإفراط الغذائي. قد يقلّل الفحم امتصاص الأدوية: افصل المآخذ بساعتين. للحامل: استشارة طبية.',
    image: 'p-colon-detox.png', featured: 1, active: 1, sort_order: 3,
  },
  {
    name: 'Confort Intestinal', name_ar: 'الراحة المعوية',
    brand: 'HERBALIS', category: 'colon', price: 27.9, old_price: null, stock: 40,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Menthe, gingembre, camomille',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '1 gélule avant les repas',
    short_fr: 'Ballonnements et spasmes, trio de plantes.',
    short_ar: 'انتفاخ وتشنجات، ثلاثي نباتي.',
    desc_fr: 'Confort Intestinal réunit menthe poivrée, gingembre et camomille pour apaiser les sensations de ballonnement et de spasme après les repas. Formule sans lactose, gélules végétales. Complément alimentaire, pas un médicament. Consultez un médecin si les douleurs persistent.',
    desc_ar: 'يجمع الراحة المعوية النعناع الفلفلي والزنجبيل والبابونج لتهدئة الإحساس بالانتفاخ والتشنج بعد الوجبات. خالٍ من اللاكتوز، كبسولات نباتية. مكمّل غذائي وليس دواء. راجع طبيباً إذا استمر الألم.',
    image: 'p-colon-flora.png', featured: 0, active: 1, sort_order: 4,
  },
  {
    name: 'Biotine Forte 5000', name_ar: 'بيوتين فورت 5000',
    brand: 'HERBALIS', category: 'hair', price: 34.9, old_price: 39.9, stock: 52,
    cpu: '90 gélules', ram: 'Cure 3 mois', storage: 'Biotine 5000 µg, zinc, sélénium',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '1 gélule par jour au petit-déjeuner',
    short_fr: 'Chute de cheveux, biotine haute dose et zinc.',
    short_ar: 'تساقط الشعر، بيوتين بجرعة عالية وزنك.',
    desc_fr: 'Biotine Forte 5000 apporte de la vitamine B8 à dose concentrée, du zinc et du sélénium, nutriments qui contribuent au maintien de cheveux normaux. Destiné aux chutes saisonnières, post-partum (après avis) ou liées au stress. Résultats visibles en général après 8 à 12 semaines de cure continue.',
    desc_ar: 'يوفر بيوتين فورت 5000 فيتامين B8 بجرعة مركّزة مع الزنك والسيلينيوم، وهي عناصر تساهم في الحفاظ على شعر طبيعي. موجّه للتساقط الموسمي أو بعد الولادة (بعد استشارة) أو المرتبط بالتوتر. تظهر النتائج عادة بعد 8 إلى 12 أسبوعاً من الاستعمال المتواصل.',
    image: 'p-hair-biotin.png', featured: 1, active: 1, sort_order: 5,
  },
  {
    name: 'Pousse & Densité', name_ar: 'الإنبات والكثافة',
    brand: 'HERBALIS', category: 'hair', price: 39.9, old_price: null, stock: 33,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Millet, L-cystine, vitamine B6',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '2 gélules le matin',
    short_fr: 'Densité capillaire, millet et cystine.',
    short_ar: 'كثافة الشعر، الدخن والسيستين.',
    desc_fr: 'Pousse & Densité cible le volume et la fibre grâce au millet, à la L-cystine et à la vitamine B6. Pour cheveux fins, clairsemés, ou après une période de chute. À combiner avec un shampoing doux et un apport protéique suffisant. Cure renouvelable 3 mois.',
    desc_ar: 'يستهدف الإنبات والكثافة الحجم والليفة عبر الدخن والسيستين وفيتامين B6. للشعر الرقيق أو الخفيف أو بعد فترة تساقط. يُفضّل دمجه مع شامبو لطيف ومدخول كافٍ من البروتين. يمكن تجديد العلاج 3 أشهر.',
    image: 'p-hair-biotin.png', featured: 1, active: 1, sort_order: 6,
  },
  {
    name: 'Anti-Chute Homme', name_ar: 'مكافحة التساقط للرجال',
    brand: 'HERBALIS', category: 'hair', price: 42.9, old_price: 49.9, stock: 24,
    cpu: '90 gélules', ram: 'Cure 3 mois', storage: 'Saw palmetto, zinc, pumpkin seed',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '1 gélule matin et soir',
    short_fr: 'Alopécie masculine, saw palmetto et zinc.',
    short_ar: 'صلع ذكوري، ساو بالميتو وزنك.',
    desc_fr: 'Anti-Chute Homme associe saw palmetto (palmier nain), zinc et huile de pépins de courge, traditionnellement utilisés pour le cuir chevelu masculin. Pensé pour une chute de type androgenétique. Ne remplace pas un traitement prescrit (minoxidil, finastéride). Bilan sanguin recommandé si la chute est brutale.',
    desc_ar: 'يجمع مكافحة التساقط للرجال ساو بالميتو والزنك وزيت بذور القرع، المستخدمة تقليدياً لفروة الرأس عند الرجال. مصمّم لتساقط من النمط الأندروجيني. لا يغني عن علاج موصوف (مينوكسيديل، فيناستريد). يُنصح بتحليل دم إذا كان التساقط مفاجئاً.',
    image: 'p-hair-biotin.png', featured: 0, active: 1, sort_order: 7,
  },
  {
    name: 'Sérum Capillaire Romarin', name_ar: 'سيروم الشعر بإكليل الجبل',
    brand: 'HERBALIS', category: 'hair', price: 29.9, old_price: null, stock: 41,
    cpu: '50 ml', ram: 'Usage quotidien', storage: 'Romarin, ricin, caféine',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '8 gouttes sur cuir chevelu sec, masser 2 min',
    short_fr: 'Sérum anti-chute, romarin et ricin.',
    short_ar: 'سيروم ضد التساقط، إكليل الجبل والخروع.',
    desc_fr: 'Sérum à appliquer sur le cuir chevelu : hydrolat de romarin, huile de ricin et caféine. Stimule localement la sensation de tonicité. Sans silicones, texture sèche. Convient aux cuirs chevelus sensibles. Éviter le contact oculaire. Résultats après 6 semaines d\'usage régulier.',
    desc_ar: 'سيروم يُوضع على فروة الرأس: ماء إكليل الجبل وزيت الخروع والكافيين. يعزّز موضعياً الإحساس بالحيوية. بدون سيليكون، قوام خفيف. مناسب للفروة الحساسة. تجنّب ملامسة العين. تظهر النتائج بعد 6 أسابيع من الاستعمال المنتظم.',
    image: 'p-hair-serum.png', featured: 1, active: 1, sort_order: 8,
  },
  {
    name: 'Kératine Végétale', name_ar: 'كيراتين نباتي',
    brand: 'HERBALIS', category: 'hair', price: 31.9, old_price: 36.9, stock: 30,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Kératine végétale, MSM, vitamine E',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '2 gélules pendant le déjeuner',
    short_fr: 'Fibre cassante, kératine vegan et MSM.',
    short_ar: 'ليفة هشّة، كيراتين نباتي وMSM.',
    desc_fr: 'Kératine Végétale (non animale) et MSM pour cheveux cassants, fourches, ou affaiblis par colorations. Complète une routine anti-chute. Convient aux régimes vegan. Hydratez aussi la fibre en externe (masque hebdomadaire).',
    desc_ar: 'كيراتين نباتي (غير حيواني) وMSM للشعر الهش أو المتقصّف أو الضعيف بسبب الصبغات. يكمّل روتيناً ضد التساقط. مناسب للنظام النباتي. رطّب الليفة أيضاً خارجياً (قناع أسبوعي).',
    image: 'p-hair-biotin.png', featured: 0, active: 1, sort_order: 9,
  },
  {
    name: 'RespiCalm', name_ar: 'ريسبكالم',
    brand: 'HERBALIS', category: 'packs', price: 36.9, old_price: null, stock: 22,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Thym, plantain, NAC, vitamine D',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: '2 gélules matin, loin des repas si estomac sensible',
    short_fr: 'Voies respiratoires, asthme et gorges irritées.',
    short_ar: 'الجهاز التنفسي، الربو والحلق المتهيّج.',
    desc_fr: 'RespiCalm réunit thym, plantain lancéolé, N-acétylcystéine et vitamine D pour le confort des voies respiratoires. Pensé pour les personnes sujettes à l\'asthme léger, aux gorges irritées ou aux saisons polliniques, en complément d\'un suivi médical. Ce n\'est pas un bronchodilatateur ni un substitut à un inhalateur prescrit. En cas de crise d\'asthme, suivez votre protocole médical.',
    desc_ar: 'يجمع ريسبكالم الزعتر ولسان الحمل وN-أسيتيل سيستئين وفيتامين D لراحة الجهاز التنفسي. موجّه لمن يعانون ربوًا خفيفًا أو حلقًا متهيّجًا أو مواسم حساسية، إلى جانب متابعة طبية. ليس موسّعاً قصبياً ولا بديلاً عن بخاخ موصوف. في نوبة الربو اتبع بروتوكولك الطبي.',
    image: 'p-respi-calm.png', featured: 1, active: 1, sort_order: 10,
  },
  {
    name: 'Cure Duo Côlon + Cheveux', name_ar: 'علاج ثنائي قولون + شعر',
    brand: 'HERBALIS', category: 'packs', price: 54.9, old_price: 64.9, stock: 18,
    cpu: '2 x 60 gélules', ram: 'Cure 1 mois', storage: 'Flora Colon + Biotine Forte',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: 'Suivre la posologie de chaque flacon',
    short_fr: 'Pack 1 mois, intestin et vitalité capillaire.',
    short_ar: 'باقة شهر، أمعاء وحيوية الشعر.',
    desc_fr: 'Le Duo associe Flora Colon et Biotine Forte pour travailler confort intestinal et chute de cheveux en parallèle, un lien souvent observé (malabsorption, stress, carences). Économie vs achat séparé. Idéal pour démarrer une première cure.',
    desc_ar: 'يجمع الثنائي فلورا كولون وبيوتين فورت للعمل على الراحة المعوية وتساقط الشعر معاً، وهو ارتباط شائع (سوء امتصاص، توتر، نواقص). أوفر من الشراء المنفصل. مناسب لبدء أول علاج.',
    image: 'p-pack-cure.png', featured: 1, active: 1, sort_order: 11,
  },
  {
    name: 'Pack Vitalité 3 mois', name_ar: 'باقة الحيوية 3 أشهر',
    brand: 'HERBALIS', category: 'packs', price: 79.9, old_price: 94.9, stock: 15,
    cpu: '3 flacons', ram: 'Cure 90 jours', storage: 'Biotine + Transit + Confort intestinal',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: 'Calendrier de cure fourni dans le colis',
    short_fr: '90 jours, digestion et pousse capillaire.',
    short_ar: '90 يوماً، هضم وإنبات الشعر.',
    desc_fr: 'Pack Vitalité 3 mois : trois flacons pour une cure continue (transit, confort digestif, biotine). La durée de 90 jours correspond au cycle de renouvellement du cheveu. Livraison en un colis, tarif lot -15 %.',
    desc_ar: 'باقة الحيوية 3 أشهر: ثلاثة عبوات لعلاج متواصل (العبور، الراحة الهضمية، البيوتين). مدة 90 يوماً توافق دورة تجدد الشعر. شحن في طرد واحد، سعر الجملة -15٪.',
    image: 'p-pack-cure.png', featured: 0, active: 1, sort_order: 12,
  },
  {
    name: 'Cure Complète 90 jours', name_ar: 'العلاج الكامل 90 يوماً',
    brand: 'HERBALIS', category: 'packs', price: 99.9, old_price: 119.9, stock: 12,
    cpu: '4 formules', ram: 'Cure 90 jours', storage: 'Côlon + Cheveux + RespiCalm',
    gpu: 'Fabriqué en France', screen: '100% Naturel|Vegan|Fabriqué en France', os: 'Protocole jour par jour dans le livret',
    short_fr: 'Côlon, cheveux et respiration, protocole 90 j.',
    short_ar: 'قولون وشعر وتنفس، بروتوكول 90 يوماً.',
    desc_fr: 'La Cure Complète couvre les trois axes HERBALIS : confort du côlon, anti-chute, et voies respiratoires (asthme léger, irritations). Quatre formules, livret de posologie, engagement 90 jours. Satisfait ou remboursé 30 jours sur le premier flacon ouvert. Complément, pas un traitement de fond.',
    desc_ar: 'يغطي العلاج الكامل محاور هيرباليس الثلاثة: راحة القولون، مكافحة التساقط، والجهاز التنفسي (ربو خفيف، تهيّج). أربع صيغ، كتيّب جرعات، التزام 90 يوماً. ضمان الرضا أو الاسترداد خلال 30 يوماً على أول عبوة مفتوحة. مكمّل وليس علاجاً أساسياً.',
    image: 'p-pack-cure.png', featured: 1, active: 1, sort_order: 13,
  },
];
