'use strict';

/** Catalogue France (€) — utilisé au premier démarrage / remplacement des démos. */
module.exports = [
  {
    name: 'Dell i5 10e - 8 Go / 256 Go SSD', brand: 'Dell', category: 'Ordinateurs', price: 199, old_price: 279, stock: 1,
    cpu: 'Intel Core i5 10e génération', ram: '8 Go', storage: 'SSD 256 Go', gpu: 'Intel UHD Graphics', screen: '14" Full HD', os: 'Windows 11',
    short_fr: 'Comme neuf. Office + antivirus offerts.', short_en: 'Like-new. Free Office + antivirus.',
    desc_fr: 'PC portable Dell i5 10e, 8 Go RAM, SSD 256 Go. Pack Office et antivirus offerts. Remise possible à Montrouge (92120).',
    desc_en: 'Dell i5 10th gen, 8 GB RAM, 256 GB SSD. Free Office + antivirus. Pickup in Montrouge (92120).',
    image: 'p-dell-white.jpg', featured: 1, active: 1, sort_order: 1,
  },
  {
    name: 'Dell Latitude 5410 - i5 10e / 16 Go', brand: 'Dell', category: 'Ordinateurs', price: 230, old_price: 299, stock: 1,
    cpu: 'Intel Core i5 10e génération', ram: '16 Go', storage: 'SSD 256 Go', gpu: 'Intel UHD Graphics', screen: '14" Full HD', os: 'Windows 11',
    short_fr: 'Comme neuf. 16 Go de RAM. Office offert.', short_en: 'Like-new. 16 GB RAM. Free Office.',
    desc_fr: 'Dell Latitude 5410, i5 10e, 16 Go RAM, SSD 256 Go. Idéal bureau / études.',
    desc_en: 'Dell Latitude 5410, i5 10th gen, 16 GB RAM, 256 GB SSD.',
    image: 'p-dell-latitude.jpg', featured: 1, active: 1, sort_order: 2,
  },
  {
    name: 'Dell i5 10e Tactile - 16 Go (ou 8 Go)', brand: 'Dell', category: 'Ordinateurs', price: 239, old_price: 319, stock: 1,
    cpu: 'Intel Core i5 10e génération', ram: '16 Go', storage: 'SSD 256 Go', gpu: 'Intel UHD Graphics', screen: '14" tactile', os: 'Windows 11',
    short_fr: 'Écran tactile. Polyvalent. Comme neuf.', short_en: 'Touchscreen. Versatile. Like-new.',
    desc_fr: 'Dell tactile i5 10e, 16 Go RAM (config 8 Go possible), SSD 256 Go.',
    desc_en: 'Touchscreen Dell i5 10th gen, 16 GB RAM, 256 GB SSD.',
    image: 'p-dell-touch.jpg', featured: 1, active: 1, sort_order: 3,
  },
  {
    name: 'Acer Nitro 5 - Gaming RTX 2060', brand: 'Acer', category: 'Gaming', price: 519, old_price: 599, stock: 0,
    cpu: 'Intel Core i5', ram: '16 Go', storage: 'SSD 512 Go', gpu: 'NVIDIA GeForce RTX 2060', screen: '15.6" 144 Hz', os: 'Windows 11',
    short_fr: 'Vendu — plus disponible.', short_en: 'Sold — no longer available.',
    desc_fr: 'Acer Nitro 5 RTX 2060. Cet exemplaire est vendu.',
    desc_en: 'Acer Nitro 5 RTX 2060. This unit is sold.',
    image: 'p-gaming-excalibur.jpg', featured: 0, active: 1, sort_order: 4,
  },
  {
    name: 'HP Victus - Gaming RTX 2060', brand: 'HP', category: 'Gaming', price: 549, old_price: null, stock: 1,
    cpu: 'AMD Ryzen 5', ram: '16 Go', storage: 'SSD 512 Go', gpu: 'NVIDIA GeForce RTX 2060', screen: '16.1" Full HD', os: 'Windows 11',
    short_fr: 'Gamer sobre et efficace, RTX 2060.', short_en: 'Clean efficient gamer, RTX 2060.',
    desc_fr: 'HP Victus RTX 2060, 16 Go, SSD 512 Go. Comme neuf.',
    desc_en: 'HP Victus RTX 2060, 16 GB, 512 GB SSD. Like-new.',
    image: 'p-gaming-hp.jpg', featured: 0, active: 1, sort_order: 5,
  },
  {
    name: 'Predator Helios 300 - Gaming RTX 2070', brand: 'Acer', category: 'Gaming', price: 599, old_price: 699, stock: 1,
    cpu: 'Intel Core i7', ram: '16 Go', storage: 'SSD 1 To', gpu: 'NVIDIA GeForce RTX 2070', screen: '15.6" 144 Hz', os: 'Windows 11',
    short_fr: 'Machine de guerre gaming. RTX 2070.', short_en: 'Gaming beast. RTX 2070.',
    desc_fr: 'Predator Helios 300 RTX 2070, 16 Go, 1 To SSD.',
    desc_en: 'Predator Helios 300 RTX 2070, 16 GB, 1 TB SSD.',
    image: 'p-gaming-rog.jpg', featured: 1, active: 1, sort_order: 6,
  },
  {
    name: 'MSI Leopard - Gaming RTX 2070', brand: 'MSI', category: 'Gaming', price: 579, old_price: 679, stock: 1,
    cpu: 'Intel Core i7', ram: '16 Go', storage: 'SSD 1 To', gpu: 'NVIDIA GeForce RTX 2070', screen: '15.6" 144 Hz', os: 'Windows 11',
    short_fr: 'Gamer nerveux. RTX 2070, 1 To SSD.', short_en: 'Fast gamer. RTX 2070, 1 TB.',
    desc_fr: 'MSI Leopard RTX 2070, 16 Go, 1 To SSD.',
    desc_en: 'MSI Leopard RTX 2070, 16 GB, 1 TB SSD.',
    image: 'p-gaming-dark.jpg', featured: 0, active: 1, sort_order: 7,
  },
  {
    name: 'ASUS TUF Gaming - RTX 3060', brand: 'Asus', category: 'Gaming', price: 699, old_price: 799, stock: 1,
    cpu: 'AMD Ryzen 7', ram: '16 Go', storage: 'SSD 512 Go', gpu: 'NVIDIA GeForce RTX 3060', screen: '15.6" 144 Hz', os: 'Windows 11',
    short_fr: 'Robuste et puissant, RTX 3060.', short_en: 'Rugged and powerful, RTX 3060.',
    desc_fr: 'ASUS TUF Gaming RTX 3060, 16 Go, SSD 512 Go.',
    desc_en: 'ASUS TUF Gaming RTX 3060, 16 GB, 512 GB SSD.',
    image: 'p-gaming-asus.jpg', featured: 1, active: 1, sort_order: 8,
  },
  {
    name: 'Lenovo Legion 5 - RTX 3060', brand: 'Lenovo', category: 'Gaming', price: 749, old_price: 849, stock: 1,
    cpu: 'AMD Ryzen 7', ram: '16 Go', storage: 'SSD 1 To', gpu: 'NVIDIA GeForce RTX 3060', screen: '15.6" 165 Hz', os: 'Windows 11',
    short_fr: 'Gaming abordable, écran 165 Hz.', short_en: 'Affordable gaming, 165 Hz.',
    desc_fr: 'Lenovo Legion 5 RTX 3060, 16 Go, 1 To SSD, 165 Hz.',
    desc_en: 'Lenovo Legion 5 RTX 3060, 16 GB, 1 TB SSD, 165 Hz.',
    image: 'p-gaming-excalibur.jpg', featured: 1, active: 1, sort_order: 9,
  },
  {
    name: 'Samsung Galaxy A54 5G - 128 Go', brand: 'Samsung', category: 'Smartphones', price: 249, old_price: 299, stock: 1,
    cpu: 'Exynos 1380', ram: '8 Go', storage: '128 Go', gpu: '', screen: '6.4" Super AMOLED 120 Hz', os: 'Android',
    short_fr: 'Best-seller milieu de gamme, 5G.', short_en: 'Mid-range best-seller, 5G.',
    desc_fr: 'Galaxy A54 5G, 8 Go / 128 Go, écran AMOLED 120 Hz. Comme neuf.',
    desc_en: 'Galaxy A54 5G, 8 GB / 128 GB. Like-new.',
    image: 'p-samsung-gray.jpg', featured: 0, active: 1, sort_order: 10,
  },
  {
    name: 'Samsung Galaxy S20 FE - 128 Go', brand: 'Samsung', category: 'Smartphones', price: 219, old_price: 279, stock: 1,
    cpu: 'Qualcomm Snapdragon', ram: '6 Go', storage: '128 Go', gpu: '', screen: '6.5" Super AMOLED 120 Hz', os: 'Android',
    short_fr: 'Flagship malin, écran 120 Hz.', short_en: 'Smart flagship, 120 Hz.',
    desc_fr: 'Galaxy S20 FE, 6 Go / 128 Go. Comme neuf.',
    desc_en: 'Galaxy S20 FE, 6 GB / 128 GB. Like-new.',
    image: 'p-samsung-s20.jpg', featured: 0, active: 1, sort_order: 11,
  },
  {
    name: 'Samsung Galaxy S22 - 128 Go (graphite)', brand: 'Samsung', category: 'Smartphones', price: 299, old_price: 379, stock: 0,
    cpu: 'Exynos / Snapdragon', ram: '8 Go', storage: '128 Go', gpu: '', screen: '6.1" Dynamic AMOLED 120 Hz', os: 'Android',
    short_fr: 'Vendu — plus disponible.', short_en: 'Sold — no longer available.',
    desc_fr: 'Galaxy S22 128 Go. Cet exemplaire est vendu.',
    desc_en: 'Galaxy S22 128 GB. This unit is sold.',
    image: 'p-samsung-s21.jpg', featured: 0, active: 1, sort_order: 12,
  },
  {
    name: 'Samsung Galaxy S22 - 128 Go', brand: 'Samsung', category: 'Smartphones', price: 379, old_price: 459, stock: 0,
    cpu: 'Qualcomm Snapdragon 8 Gen 1', ram: '8 Go', storage: '128 Go', gpu: '', screen: '6.1" Dynamic AMOLED 120 Hz', os: 'Android',
    short_fr: 'Vendu — plus disponible.', short_en: 'Sold — no longer available.',
    desc_fr: 'Galaxy S22 premium. Cet exemplaire est vendu.',
    desc_en: 'Galaxy S22 premium. This unit is sold.',
    image: 'p-samsung-ultra.jpg', featured: 0, active: 1, sort_order: 13,
  },
];
