'use strict';

const BRAND = 'معشبة الأطلس';

const COLON_PRODUCT = {
  name: 'Confort côlon', name_ar: 'راحة القولون',
  brand: BRAND, category: 'colon', price: 189, old_price: 229, stock: 64,
  cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Inuline, fenouil, menthe',
  gpu: 'المغرب', screen: '100% Naturel|Vegan', os: '1 gélule matin et soir',
  short_fr: 'Ballonnements et transit, plantes douces.',
  short_ar: 'انتفاخ وعبور معوي، نباتات لطيفة.',
  desc_fr: 'Formule côlon : fibres et plantes (fenouil, menthe) pour un ventre plus calme. Cure 30 jours. Beaucoup d\'eau. Avis médical si douleur persistante.',
  desc_ar: 'صيغة القولون: ألياف ونباتات (شمر، نعناع) لبطن أهدأ. علاج 30 يوماً. ماء كثير. استشارة طبية إذا استمر الألم.',
  image: 'p-colon-flora.png', featured: 1, active: 1, sort_order: 2,
};

/** 4 produits + 2 extra SKUs côlon + packs. Prix MAD. */
module.exports = [
  {
    name: 'Miel naturel', name_ar: 'عسل حر طبيعي',
    brand: BRAND, category: 'honey', price: 249, old_price: 349, stock: 80,
    cpu: '250 غ', ram: 'علبة زجاج', storage: 'عسل حر، بدون سكر مضاف',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: 'ملعقة صغيرة صباحاً أو مساءً',
    short_fr: 'Miel brut, gorge et énergie du quotidien.',
    short_ar: 'عسل حر للحلق والطاقة اليومية.',
    desc_fr: 'Miel naturel non chauffé. Utile pour adoucir la gorge et remplacer le sucre. Une cuillère par jour, ou dans un thé tiède. Pas pour les enfants de moins d\'un an. Complément, pas un médicament.',
    desc_ar: 'عسل حر غير مسخّن. يهدّئ الحلق ويعوّض السكر. ملعقة في اليوم، أو في شاي دافئ. ممنوع للأطفال أقل من سنة. مكمّل، ليس دواء.',
    image: 'honey-hero.png', featured: 1, active: 1, sort_order: 1,
  },
  COLON_PRODUCT,
  { ...COLON_PRODUCT, sort_order: 8 },
  { ...COLON_PRODUCT, sort_order: 9 },
  {
    name: 'Anti-chute', name_ar: 'كثافة الشعر',
    brand: BRAND, category: 'hair', price: 199, old_price: 249, stock: 70,
    cpu: '90 gélules', ram: 'Cure 3 mois', storage: 'Biotine, zinc, millet',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: '1 gélule au petit-déjeuner',
    short_fr: 'Chute de cheveux, biotine et zinc.',
    short_ar: 'تساقط الشعر، بيوتين وزنك.',
    desc_fr: 'Biotine, zinc et millet pour cheveux qui tombent au lavage. Comptez 8 à 12 semaines. Ne remplace pas un traitement prescrit.',
    desc_ar: 'بيوتين وزنك ودخن للشعر اللي كيطاح فالغسيل. 8 إلى 12 أسبوع. ما كيعوّضش علاج موصوف.',
    image: 'p-hair-biotin.png', featured: 1, active: 1, sort_order: 3,
  },
  {
    name: 'Confort asthme', name_ar: 'نفس مرتاح',
    brand: BRAND, category: 'respi', price: 219, old_price: 269, stock: 55,
    cpu: '60 gélules', ram: 'Cure 1 mois', storage: 'Thym, plantain, nigelle',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: '2 gélules le matin',
    short_fr: 'Voies respiratoires, asthme léger, gorge irritée.',
    short_ar: 'الجهاز التنفسي، ربو خفيف، حلق متهيّج.',
    desc_fr: 'Thym, plantain et nigelle pour le confort respiratoire (asthme léger, saison, poussière). Ce n\'est pas un inhalateur. En crise, suivez votre protocole médical.',
    desc_ar: 'زعتر ولسان الحمل وحبة البركة لراحة التنفس (ربو خفيف، موسم، غبار). ماشي بخاخ. فالنوبة تبع بروتوكولك الطبي.',
    image: 'p-respi-calm.png', featured: 1, active: 1, sort_order: 4,
  },
  {
    name: 'Pack côlon + cheveux', name_ar: 'باقة القولون والشعر',
    brand: BRAND, category: 'packs', price: 349, old_price: 428, stock: 28,
    cpu: '2 formules', ram: 'Cure 1 mois', storage: 'راحة القولون + كثافة الشعر',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: 'Suivre chaque flacon',
    short_fr: 'Duo ventre et chute de cheveux.',
    short_ar: 'ثنائي البطن وتساقط الشعر.',
    desc_fr: 'Les deux formules côlon et cheveux, tarif lot. Livraison 24 h Rabat / Salé / Casa, 48 h ailleurs.',
    desc_ar: 'صيغتا القولون والشعر بسعر الجملة. توصيل 24 ساعة الرباط سلا البيضاء، 48 ساعة باقي المدن.',
    image: 'p-pack-cure.png', featured: 1, active: 1, sort_order: 5,
  },
  {
    name: 'Pack miel + asthme', name_ar: 'باقة العسل والتنفس',
    brand: BRAND, category: 'packs', price: 399, old_price: 468, stock: 24,
    cpu: '2 formules', ram: 'Cure 1 mois', storage: 'عسل حر + نفس مرتاح',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: 'Miel le soir, gélules le matin',
    short_fr: 'Miel et confort respiratoire.',
    short_ar: 'عسل وراحة تنفسية.',
    desc_fr: 'Miel naturel + formule asthme. Idéal saison froide. Ne remplace pas un traitement de fond.',
    desc_ar: 'عسل حر + صيغة الربو. مناسب للبرد. ما كيعوّضش علاج أساسي.',
    image: 'p-respi-calm.png', featured: 0, active: 1, sort_order: 6,
  },
  {
    name: 'Pack Maachabat Al Atlas complet', name_ar: 'باقة معشبة الأطلس الكاملة',
    brand: BRAND, category: 'packs', price: 699, old_price: 856, stock: 18,
    cpu: '4 formules', ram: 'Cure 30 jours', storage: 'عسل + قولون + شعر + ربو',
    gpu: 'المغرب', screen: '100% Naturel|Vegan', os: 'Livret de posologie dans le colis',
    short_fr: 'Les 4 produits, tarif famille.',
    short_ar: 'المنتجات الأربعة، سعر العائلة.',
    desc_fr: 'Les quatre formules معشبة الأطلس : miel, côlon, cheveux, asthme. Économie vs à l\'unité. Paiement à la livraison.',
    desc_ar: 'الصيغ الأربع ديال معشبة الأطلس: عسل، قولون، شعر، ربو. أوفر من الشراء فرادى. الدفع عند الاستلام.',
    image: 'p-pack-cure.png', featured: 1, active: 1, sort_order: 7,
  },
];
